ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
   EXECUTE IMMEDIATE 'DROP USER FlexInvest CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/
CREATE USER FlexInvest IDENTIFIED BY FlexInvest123;
GRANT ALL PRIVILEGES TO FlexInvest;
GRANT DBA TO FlexInvest;

BEGIN
   EXECUTE IMMEDIATE 'DROP USER AdminFI CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/
CREATE USER AdminFI IDENTIFIED BY Admin123;
GRANT ALL PRIVILEGES TO AdminFI;
GRANT DBA TO AdminFI;

EXIT;
